name: Netlify Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Build with dotnet
      run: dotnet build StandUpCore/StandUpCore.csproj --configuration Release
    
    - name: Publish Blazor WASM using dotnet
      run: dotnet publish StandUpCore/StandUpCore.csproj -c Release --no-build -o ./
    
    - name: Publish generated Blazor files to Netlify
      uses: netlify/actions/cli@master
      with:
          args: deploy --dir=wwwroot --prod # push wwwroot folder to Netlify
      env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
